PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 

SELECT DISTINCT
#urlVar 
?label ?depiction ?type FROM <http://dbpedia.org> WHERE {
	#encUrl a ?type .
				
	OPTIONAL { 
	  #encUrl <http://www.w3.org/2000/01/rdf-schema#label> ?label .
	  #ReplaceByLangFilter
	}
						
	OPTIONAL {
		{ #encUrl foaf:depiction ?depiction . } UNION 
		{ #encUrl dbo:thumbnail ?depiction . } 
	}
	
	#ReplaceByFilter
} #ReplaceByLimit

