PREFIX xlime: <http://xlime-project.org/vocab/> 
PREFIX sioc: <http://rdfs.org/sioc/ns#>
PREFIX ma: <http://www.w3.org/ns/ma-ont#> 

SELECT DISTINCT ?g ?ent ?confidence ?start ?end {
GRAPH ?g { 
	#encUrl a ma:SubtitleTrack.
	#encUrl xlime:hasAnnotation ?a.
	?a xlime:hasEntity ?ent.
	?a xlime:hasConfidence ?confidence.
	OPTIONAL {
		?a xlime:hasPosition ?pos.
		?pos xlime:hasStartPosition ?start.
		?pos xlime:hasStopPosition ?end.
	}
} #end of Graph ?g
}

